# Generated by Django 4.2 on 2023-05-23 02:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='players',
            field=models.ManyToManyField(related_name='organization_players', to=settings.AUTH_USER_MODEL),
        ),
    ]
