# Generated by Django 4.2 on 2023-04-20 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogwriter',
            name='email',
        ),
        migrations.RemoveField(
            model_name='blogwriter',
            name='name',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='email',
        ),
        migrations.RemoveField(
            model_name='organizer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='organizer',
            name='name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='name',
        ),
        migrations.AlterField(
            model_name='blogwriter',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='blogwriter',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='media/images/blog_profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='blogwriter',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, upload_to='media/images/organization_logos/'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='logo',
            field=models.ImageField(blank=True, upload_to='media/images/organizer_logos/'),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='profile_picture',
            field=models.ImageField(blank=True, upload_to='media/images/player_profile_pictures/'),
        ),
    ]
