# Generated by Django 4.2 on 2023-04-11 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_player_organizer_organization_blogwriter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
