# Generated by Django 4.2 on 2023-05-23 03:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_organization_players'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('request_started_by', models.CharField(choices=[('Player', 'Player'), ('Organization', 'Organization')], default='Organization', max_length=500)),
                ('request_status', models.CharField(choices=[('Requested', 'Requested'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Organization', max_length=500)),
                ('remarks', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='organization_request', to='account.organization')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='player_request', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
