# Generated by Django 4.2 on 2023-05-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userprofile_is_verified_userprofile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Player', 'Player'), ('Organization', 'Organization'), ('Organizer', 'Organizer'), ('Blog Writer', 'Blog Writer'), ('Admin', 'Admin')], max_length=15),
        ),
    ]
