# Generated by Django 4.2 on 2023-04-12 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogwriter',
            name='profile_picture',
            field=models.ImageField(upload_to='media/images/blog_profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(upload_to='media/images/organization_logos/'),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='logo',
            field=models.ImageField(upload_to='media/images/organizer_logos/'),
        ),
        migrations.AlterField(
            model_name='player',
            name='profile_picture',
            field=models.ImageField(upload_to='media/images/player_profile_pictures/'),
        ),
    ]
