# Generated by Django 4.2 on 2023-05-07 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_userprofile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogwriter',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='blogwriter',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='address',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='description',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='website',
        ),
        migrations.RemoveField(
            model_name='organizer',
            name='description',
        ),
        migrations.RemoveField(
            model_name='organizer',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='organizer',
            name='website',
        ),
        migrations.RemoveField(
            model_name='player',
            name='country',
        ),
        migrations.RemoveField(
            model_name='player',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='player',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='blogwriter',
            name='position',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='organizer',
            name='organization_name',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nationality',
            field=models.CharField(default='Nepalese', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_name',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('Twitter', 'Twitter'), ('Instagram', 'Instagram'), ('Facebook', 'Facebook'), ('YouTube', 'YouTube'), ('Twitch', 'Twitch'), ('Website', 'Website'), ('Discord', 'Discord'), ('Reddit', 'Reddit'), ('Other', 'Other')], max_length=20)),
                ('url', models.URLField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Social media',
            },
        ),
    ]
