# Generated by Django 4.2 on 2023-05-26 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_organization_user_alter_organizer_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizer',
            old_name='organization_name',
            new_name='organizer_name',
        ),
    ]
