# Generated by Django 4.2 on 2023-06-03 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='tournament_short_description',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tournament_status',
            field=models.CharField(choices=[('Live', 'Live'), ('Past', 'Past'), ('Upcoming', 'Upcoming')], default='Upcoming', max_length=50),
        ),
    ]
