# Generated by Django 4.2 on 2023-04-17 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='schedule',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
