# Generated by Django 4.2 on 2023-05-14 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamTournamentBracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveSmallIntegerField()),
                ('rounds_per_match', models.IntegerField()),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(auto_now=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('number_of_teams', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('loser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_lost_brackets', to='tournament.team')),
                ('participants', models.ManyToManyField(related_name='Team_participants', to='account.player')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.tournament')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_won_brackets', to='tournament.team')),
            ],
            options={
                'ordering': ['round_number'],
            },
        ),
        migrations.CreateModel(
            name='SoloTournamentBracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveSmallIntegerField()),
                ('rounds_per_match', models.IntegerField()),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(auto_now=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('number_of_teams', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('loser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_brackets', to='account.player')),
                ('participants', models.ManyToManyField(related_name='participants', to='account.player')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.tournament')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='won_brackets', to='account.player')),
            ],
            options={
                'ordering': ['round_number'],
            },
        ),
    ]
