# Generated by Django 4.2 on 2023-04-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='banner_image',
            field=models.ImageField(null=True, upload_to='tournament_banners/'),
        ),
    ]
