# Generated by Django 4.2 on 2023-05-26 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_event_event_thumbnail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_thumbnail_description',
            new_name='event_thumbnail_alt_description',
        ),
    ]
