# Generated by Django 4.2 on 2023-05-15 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_teamtournamentbracket_solotournamentbracket'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoserBracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_number', models.PositiveSmallIntegerField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='LoserBracket_Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_number', models.PositiveSmallIntegerField()),
                ('loser_bracket_loser_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_loser_1', to='tournament.loserbracket')),
                ('loser_bracket_loser_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_loser_2', to='tournament.loserbracket')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='TournamentBracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bracket_type', models.CharField(choices=[('Winner Bracket', 'Winner Bracket'), ('Looser Bracket', 'Looser Bracket')], max_length=30)),
                ('participants', models.ManyToManyField(related_name='Team_participants', to='tournament.team')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='WinnerBracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_number', models.PositiveSmallIntegerField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.tournament')),
            ],
        ),
        migrations.CreateModel(
            name='WinnerBracket_Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_number', models.PositiveSmallIntegerField()),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.tournament')),
                ('winner_bracket_winner_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_winner_1', to='tournament.winnerbracket')),
                ('winner_bracket_winner_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_winner_2', to='tournament.winnerbracket')),
            ],
        ),
        migrations.RemoveField(
            model_name='teamtournamentbracket',
            name='loser',
        ),
        migrations.RemoveField(
            model_name='teamtournamentbracket',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='teamtournamentbracket',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='teamtournamentbracket',
            name='winner',
        ),
        migrations.DeleteModel(
            name='SoloTournamentBracket',
        ),
        migrations.DeleteModel(
            name='TeamTournamentBracket',
        ),
    ]
