# Generated by Django 4.2 on 2023-04-12 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_alter_tournament_banner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='logo',
            field=models.ImageField(null=True, upload_to='sponsor_logos/'),
        ),
    ]
