# Generated by Django 4.2 on 2023-05-15 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_loserbracket_loserbracket_match_tournamentbracket_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoserBracketMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_number', models.PositiveIntegerField()),
                ('loser_team_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loser_team_1_matches', to='tournament.team')),
                ('loser_team_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loser_team_2_matches', to='tournament.team')),
                ('tournament_bracket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loser_bracket_matches', to='tournament.tournamentbracket')),
            ],
        ),
        migrations.CreateModel(
            name='WinnerBracketMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_number', models.PositiveIntegerField()),
                ('tournament_bracket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner_bracket_matches', to='tournament.tournamentbracket')),
                ('winner_team_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner_team_1_matches', to='tournament.team')),
                ('winner_team_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner_team_2_matches', to='tournament.team')),
            ],
        ),
        migrations.RemoveField(
            model_name='loserbracket_match',
            name='loser_bracket_loser_1',
        ),
        migrations.RemoveField(
            model_name='loserbracket_match',
            name='loser_bracket_loser_2',
        ),
        migrations.RemoveField(
            model_name='loserbracket_match',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='winnerbracket',
            name='team',
        ),
        migrations.RemoveField(
            model_name='winnerbracket',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='winnerbracket_match',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='winnerbracket_match',
            name='winner_bracket_winner_1',
        ),
        migrations.RemoveField(
            model_name='winnerbracket_match',
            name='winner_bracket_winner_2',
        ),
        migrations.DeleteModel(
            name='LoserBracket',
        ),
        migrations.DeleteModel(
            name='LoserBracket_Match',
        ),
        migrations.DeleteModel(
            name='WinnerBracket',
        ),
        migrations.DeleteModel(
            name='WinnerBracket_Match',
        ),
    ]
