# Generated by Django 4.2 on 2023-05-26 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_event_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsponsor',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
