# Generated by Django 4.2 on 2023-05-15 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_loserbracketmatch_winnerbracketmatch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentbracket',
            name='team',
        ),
    ]
