# Generated by Django 4.2 on 2023-05-18 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_remove_tournamentbracket_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='winnerbracketmatch',
            name='tournament_bracket',
        ),
        migrations.RemoveField(
            model_name='winnerbracketmatch',
            name='winner_team_1',
        ),
        migrations.RemoveField(
            model_name='winnerbracketmatch',
            name='winner_team_2',
        ),
        migrations.DeleteModel(
            name='LoserBracketMatch',
        ),
        migrations.DeleteModel(
            name='WinnerBracketMatch',
        ),
    ]
