# Generated by Django 4.2 on 2023-05-26 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_eventsponsor_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tournament.event'),
            preserve_default=False,
        ),
    ]
