# Generated by Django 4.2 on 2023-06-03 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_remove_tournamentsponsor_sponsor_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentsponsor',
            name='sponsor_logo',
        ),
        migrations.AddField(
            model_name='tournamentsponsor',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
