# Generated by Django 4.2 on 2023-06-03 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0007_eventsponsor_sponsor_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournamentstreams',
            old_name='stream_name',
            new_name='stream_title',
        ),
    ]
