# Generated by Django 4.2 on 2023-06-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0008_rename_stream_name_tournamentstreams_stream_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='tournament_participants',
            field=models.CharField(choices=[('Player', 'Player'), ('Team', 'Team')], default='Team', max_length=700),
        ),
    ]
