# Generated by Django 4.2 on 2023-06-09 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0009_alter_tournament_tournament_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentfaq',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='tournament.tournament'),
        ),
        migrations.AlterField(
            model_name='tournamentsponsor',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsors', to='tournament.tournament'),
        ),
        migrations.AlterField(
            model_name='tournamentstreams',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='tournament.tournament'),
        ),
    ]
