# Generated by Django 4.2 on 2023-06-13 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0010_alter_tournamentfaq_tournament_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
