# Generated by Django 4.2 on 2023-06-13 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0011_event_is_verified_tournament_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamgroup',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='teamgroup',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='tournamentbracket',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='tournamentbracket',
            name='tournament',
        ),
        migrations.RenameField(
            model_name='stage',
            old_name='no_of_groups',
            new_name='input_no_of_teams',
        ),
        migrations.RenameField(
            model_name='stage',
            old_name='no_of_participants',
            new_name='output_no_of_teams',
        ),
        migrations.RemoveField(
            model_name='solomatch',
            name='group',
        ),
        migrations.RemoveField(
            model_name='solotournamentregistration',
            name='current_stage',
        ),
        migrations.RemoveField(
            model_name='teammatch',
            name='group',
        ),
        migrations.RemoveField(
            model_name='teamtournamentregistration',
            name='current_stage',
        ),
        migrations.AddField(
            model_name='stage',
            name='input_teams',
            field=models.ManyToManyField(related_name='input_teams', to='tournament.team'),
        ),
        migrations.AddField(
            model_name='stage',
            name='output_teams',
            field=models.ManyToManyField(related_name='output_teams', to='tournament.team'),
        ),
        migrations.AlterField(
            model_name='teammatch',
            name='team1_result',
            field=models.CharField(choices=[('WIN', 'WIN'), ('LOSE', 'LOSE'), ('DRAW', 'DRAW'), ('ABORTED', 'ABORTED'), ('ABORTED', 'ABORTED')], max_length=500),
        ),
        migrations.AlterField(
            model_name='teammatch',
            name='team2_result',
            field=models.CharField(choices=[('WIN', 'WIN'), ('LOSE', 'LOSE'), ('DRAW', 'DRAW'), ('ABORTED', 'ABORTED'), ('ABORTED', 'ABORTED')], max_length=500),
        ),
        migrations.DeleteModel(
            name='SoloGroup',
        ),
        migrations.DeleteModel(
            name='TeamGroup',
        ),
        migrations.DeleteModel(
            name='TournamentBracket',
        ),
    ]
