# Generated by Django 4.2 on 2023-06-13 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_rename_organization_name_organizer_organizer_name'),
        ('tournament', '0012_remove_teamgroup_participants_remove_teamgroup_stage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='tournament.event'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game', to='tournament.game'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizer', to='account.organizer'),
        ),
    ]
