# Generated by Django 4.2 on 2023-06-13 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0013_alter_tournament_event_alter_tournament_game_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
