# Generated by Django 4.2 on 2023-06-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0014_event_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='no_of_participants',
            field=models.IntegerField(default=0),
        ),
    ]
