# Generated by Django 4.2 on 2023-06-13 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0015_tournament_no_of_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solotournamentregistration',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solo_registrations', to='tournament.tournament'),
        ),
        migrations.AlterField(
            model_name='teamtournamentregistration',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_registrations', to='tournament.tournament'),
        ),
    ]
