# Generated by Django 4.2 on 2023-04-12 06:27

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(help_text='Artcile Category Name', max_length=50)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('thumbnail_image', models.ImageField(upload_to='static/images')),
                ('thumbnail_image_alt_description', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=300)),
                ('article_content', ckeditor.fields.RichTextField(max_length=500)),
                ('time_to_read', models.PositiveSmallIntegerField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('meta_title', models.CharField(max_length=200)),
                ('meta_description', models.TextField(max_length=400)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='author', to='account.blogwriter')),
                ('c_name', models.ManyToManyField(help_text='Article Category', related_name='categories', to='blog.articlecategory')),
                ('tags', models.ManyToManyField(related_name='tags', to='blog.tag')),
            ],
        ),
    ]
