# Generated by Django 4.2 on 2023-04-30 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlecategory',
            name='image',
        ),
    ]
