# Generated by Django 4.2 on 2023-05-02 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_category_name_article_categories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='time_to_read',
        ),
    ]
