# Generated by Django 4.2 on 2023-04-30 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_articlecategory_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlecategory',
            name='description',
        ),
    ]
