# Generated by Django 4.2 on 2023-04-24 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_comment_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_type',
            field=models.CharField(choices=[('Blog', 'Blog'), ('News', 'News'), ('Events', 'Events')], default='Blog', max_length=500),
        ),
    ]
