from django.urls import path
from .views import (create_elimination_mode, create_event, create_event_news_feed, create_game, create_stage, create_tournament_stream, delete_elimination_mode, delete_event_news_feed, delete_game, delete_stage, 
                    delete_tournament_stream, elimination_mode_list, game_list,create_event_faq, event_tournaments_list, get_elimination_mode, get_event_news_feed,get_event_sponsor,get_event_sponsor_detail,
                    all_event_list,get_event_faq,create_event_sponsor, create_team, create_tournament, create_tournament_faq, create_tournament_sponsor, delete_event, delete_event_faq, 
                    delete_event_sponsor, delete_tournament, delete_tournament_faq, delete_tournament_sponsor, event_detail, event_list, delete_team, get_game, open_registration, register_team, registered_teams, retrieve_team, 
                    stage,tournament_details, stage_list, tournament_detail, tournament_faq, tournament_faq_list, tournament_sponsor, tournament_sponsor_list, tournament_stream, tournament_stream_list, tournaments_list, update_elimination_mode,update_event,get_my_team, 
                    update_event_faq, update_event_news_feed, update_event_sponsor, update_game, update_stage,update_team,create_team_initials, update_tournament, update_tournament_faq, update_tournament_sponsor, update_tournament_stream
)
urlpatterns = [
    path('create-event/', create_event, name='create_event'),
    path('update-event/', update_event, name='update_event'),
    path('all-events/', all_event_list, name='all_event_list'),
    path('events/', event_list, name='events'),
    path('event-detail/', event_detail, name= 'event_detail'),
    path('delete-event/', delete_event, name='delete_event'),
    path('get-event-faqs/', get_event_faq, name='get_event_faq'),
    path('create-event-faq/', create_event_faq, name='create_event_faq'),
    path('update-event-faq/', update_event_faq, name='update_event_faq'),
    path('delete-event-faq/', delete_event_faq, name='delete_event_faq'),
    path('create-event-news-feed/', create_event_news_feed, name='create_event_news_feed'),
    path('get-event-news-feed/', get_event_news_feed, name='get_event_news_feed'),
    path('update-event-news-feed/', update_event_news_feed, name='update_event_news_feed'),
    path('delete-event-news-feed/', delete_event_news_feed, name='delete_event_news_feed'),
    path('get-event-sponsors/', get_event_sponsor, name='get_event_sponsor'),
    path('get-event-sponsor-detail/', get_event_sponsor_detail, name='get_event_sponsor_detail'),
    path('create-event-sponsor/', create_event_sponsor, name='create_event_sponsor'),
    path('update-event-sponsor/', update_event_sponsor, name='update_event_sponsor'),
    path('delete-event-sponsor/', delete_event_sponsor, name='delete_event_sponsor'),
    path('get-my-team/', get_my_team, name='get_my_team'),
    path('create-team-initials/', create_team_initials, name='create_team_initials'),
    path('retrieve-team-detail/', retrieve_team, name='retrieve_team'),
    path('create-team/', create_team, name='create_team'),
    path('update-team/', update_team, name='create_team'),
    path('delete-team/', delete_team, name='delete_team'),
    path('create-game/', create_game, name='create_game'),
    path('get-game/', get_game, name='get_game'),
    path('game-list', game_list, name='game_list'),
    path('update-game/', update_game, name='update_game'),
    path('delete-game/', delete_game, name='delete_game'),
    path('create-elimination-mode/', create_elimination_mode, name='create_elimination_mode'),
    path('get-elimination-mode/', get_elimination_mode, name='get_elimination_mode'),
    path('elimination-mode-list/', elimination_mode_list, name='elimination_mode_list'),
    path('update-elimination-mode/', update_elimination_mode, name='update_elimination_mode'),
    path('delete-elimination-mode/', delete_elimination_mode, name='delete_elimination_mode'),
    path('event-tournaments/', event_tournaments_list, name='event_tournaments_list'),
    path('create-tournament/', create_tournament, name='create_tournament'),
    path('update-tournament/', update_tournament, name='update_tournament'),
    path('delete-tournament/', delete_tournament, name='delete_tournament'),
    path('open-registration/', open_registration, name='open_registration'),
    path('tournaments/', tournaments_list, name='tournaments'),
    path('get-tournament-detail/', tournament_details, name= 'tournament_details'),
    path('tournament-detail/<int:id>/', tournament_detail, name= 'tournament_detail'),
    path('create-tournament-sponsors/', create_tournament_sponsor, name='create_tournament_sponsor'),
    path('update-tournament-sponsors/', update_tournament_sponsor, name='update_tournament_sponsor'),
    path('delete-tournament-sponsors/', delete_tournament_sponsor, name='delete_tournament_sponsor'),
    path('create-tournament-faqs/', create_tournament_faq, name='create_tournament_faq'),
    path('update-tournament-faqs/', update_tournament_faq, name='update_tournament_faq'),
    path('delete-tournament-faqs/', delete_tournament_faq, name='delete_tournament_faq'),
    path('tournament-faqs-list/', tournament_faq_list, name='tournament_faq_list'),
    path('tournament-faq/', tournament_faq, name='tournament_faq'),
    path('tournament-sponsor/', tournament_sponsor, name='tournament_sponsor'),
    path('tournament-sponsors-list/', tournament_sponsor_list, name='tournament_sponsor_list'),
    path('create-tournament-stream/', create_tournament_stream, name='create_tournament_stream'),
    path('tournament-stream-list/', tournament_stream_list, name='tournament_stream_list'),
    path('tournament-stream/', tournament_stream, name='tournament_stream'),
    path('update-tournament-stream/', update_tournament_stream, name='update_tournament_stream'),
    path('delete-tournament-stream/', delete_tournament_stream, name='delete_tournament_stream'),
    path('create-tournament-stage/', create_stage, name='create_stage'),
    path('tournament-stage_list/', stage_list, name='stage_list'),
    path('tournament-stage/', stage, name='stage'),
    path('update-tournament-stage/', update_stage, name='update_stage'),
    path('delete-tournament-stage/', delete_stage, name='delete_stage'),
    path('registered-teams/', registered_teams, name='registered_teams'),
    path('register-team/', register_team, name='register_team'),

]
