from django.urls import path
from .views import create_event, create_event_faq, event_tournaments_list,get_event_sponsor,get_event_sponsor_detail,all_event_list,get_event_faq,create_event_sponsor, create_team, create_tournament, create_tournament_faq, create_tournament_sponsor, delete_event, delete_event_faq, delete_event_sponsor, delete_tournament, delete_tournament_faq, delete_tournament_sponsor, event_detail, event_list, delete_team, retrieve_team, tournament_detail, tournament_faq, tournament_faq_list, tournament_sponsor, tournament_sponsor_list, tournaments_list,update_event,get_my_team, update_event_faq, update_event_sponsor,update_team,create_team_initials, update_tournament, update_tournament_faq, update_tournament_sponsor

urlpatterns = [
    path('create-event/', create_event, name='create_event'),
    path('update-event/', update_event, name='update_event'),
    path('all-events/', all_event_list, name='all_event_list'),
    path('events/', event_list, name='events'),
    path('event-detail/', event_detail, name= 'event_detail'),
    path('delete-event/', delete_event, name='delete_event'),
    path('get-event-faqs/', get_event_faq, name='get_event_faq'),
    path('create-event-faq/', create_event_faq, name='create_event_faq'),
    path('update-event-faq/', update_event_faq, name='update_event_faq'),
    path('delete-event-faq/', delete_event_faq, name='delete_event_faq'),
    path('get-event-sponsors/', get_event_sponsor, name='get_event_sponsor'),
    path('get-event-sponsor-detail/', get_event_sponsor_detail, name='get_event_sponsor_detail'),
    path('create-event-sponsor/', create_event_sponsor, name='create_event_sponsor'),
    path('update-event-sponsor/', update_event_sponsor, name='update_event_sponsor'),
    path('delete-event-sponsor/', delete_event_sponsor, name='delete_event_sponsor'),
    path('get-my-team/', get_my_team, name='get_my_team'),
    path('create-team-initials/', create_team_initials, name='create_team_initials'),
    path('retrieve-team-detail/', retrieve_team, name='retrieve_team'),
    path('create-team/', create_team, name='create_team'),
    path('update-team/', update_team, name='create_team'),
    path('delete-team/', delete_team, name='delete_team'),
    path('create-tournament/', create_tournament, name='create_tournament'),
    path('update-tournament/', update_tournament, name='update_tournament'),
    path('tournaments/', tournaments_list, name='tournaments'),
    path('event-tournaments/', event_tournaments_list, name='event_tournaments_list'),
    path('tournament-detail/', tournament_detail, name= 'tournament_detail'),
    path('delete-tournament/', delete_tournament, name='delete_tournament'),
    path('tournament-sponsors/', create_tournament_sponsor, name='create_tournament_sponsor'),
    path('tournament-sponsors/', update_tournament_sponsor, name='update_tournament_sponsor'),
    path('tournament-sponsors/', delete_tournament_sponsor, name='delete_tournament_sponsor'),
    path('tournament-faqs/', create_tournament_faq, name='create_tournament_faq'),
    path('tournament-faqs/', update_tournament_faq, name='update_tournament_faq'),
    path('tournament-faqs/', delete_tournament_faq, name='delete_tournament_faq'),
    path('tournament-faqs-list/', tournament_faq_list, name='tournament_faq_list'),
    path('tournament-faq/', tournament_faq, name='tournament_faq'),
    path('tournament-sponsor/', tournament_sponsor, name='tournament_sponsor'),
    path('tournament-sponsors-list/', tournament_sponsor_list, name='tournament_sponsor_list'),

]
